### ISSUE TITLE
Data Visualization Challenge - Submit Your Solutions

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/housing-data-visualization-project#1]
### Background

BC Innovation Council, BC Stats, and BC Centre for Data Innovation are inviting B.C. innovators and data visualization experts to submit ‘Letters of Interest’ explaining how they can support and solve data visualization opportunities using government and other sources of data. In this specific example, the data visualization challenge is being applied to B.C. Housing market data.

Letters of Interest will be reviewed by a panel of experts. The top five submissions will receive $10,000 and mentorship from the BC Innovation Council and BC Stats to develop their prototypes. The best solution will be chosen at the #BCTECH Summit and will benefit from an additional $25,000 for continued development. 

### User Story

As a government program owner I need to be able to improve our data visualization capacity and the usefulness of Crown data so that large volumes of data are more accessible, understandable and support government in evidence-based decision making.

### Acceptance Criteria

1. Demonstrate innovative technology that is practical and engaging;
2. Utilize open source tools and coding as much as possible; and
3. Deliver a platform that can visualize, interpret and model data for use by the Provincial Government.
 

### How to Contribute (How to Apply)

Complete and submit [the ‘Letter of Interest’ form](https://github.com/bcgov/housing-data-visualization-project/blob/master/Challenge_LOI_Form.pdf) by Tuesday January 10, 2017 at 4:00pm PST via email to the BC Innovation Council at connect@bcic.ca (Subject Line: Data Visualization Challenge, Letter of Interest). The ‘Letter of Interest’ can be a maximum of two-pages, and must be submitted in arial 10 font. Condensed fonts will not be accepted. Submissions are welcome from all B.C. innovators.

Non-Confidential: All content provided in the ‘Letter of Interest' must be public. Please understand that by signing and submitting the ‘Letter of Interest’ you are acknowledging that the content provided is non-confidential information about your company, idea or innovation, and that the BC Innovation Council will be contacting you to discuss your submission and will share this information with reviewers as part of the evaluation process.

### How the challenge works:

Competing submissions from B.C. tech companies will move through three stages. Interested parties will submit a Letter of Interest providing initial information on their background and the proposed solution. The top five submissions will receive $10,000 and mentorship from BC Innovation Council and BC Stats to develop their prototypes. The best solution will be chosen at the #BCTECH Summit, and will benefit from an additional $25,000 to be put towards continued development of the visualization platform.

- January 10, 2017: Letters of Interest submitted describing potential solutions
- Late January, 2017: Panel selects up to 5 submissions as winners to move onto the next stage
- Late February, 2017: Innovation Sprint - Development of prototypes that address customer requirements
- March 14 to 15, 2017: Panel selection of winner at #BCTECHSummit
- March 15 to June 30, 2017: Design Sprint - On-going development of the winning solution
 

### What to include in your proposal (evaluation criteria)

The solutions that visualize the B.C. Housing market data should have the potential to be applied to data visualization needs in other areas of government, using various sources of data (model data, actual government data, and external industry data). In addition, solutions should incorporate the use of a collaborative platform that makes it easy for government teams and service providers to share code, works-in-progress and open data related to the visualizations (B.C. Government GitHub space is preferred). Potential use cases of such a platform are extensive and the intention is to generate visualizations that can easily and cost-effectively be shared by government through engagement platforms (i.e. online, social media, events). 

The visualization should be designed with the assumption that additional types of housing-related data will be integrated in the future. The visualizations should also provide useful and engaging experiences, as in the following examples:

- Locating neighborhood diversity in the American metropolis (created using the open source statistical software R)
https://walkerke.shinyapps.io/neighborhood_diversity/

- Growth Potential of Baltimore Neighbourhoods http://files.zillowstatic.com/research/public/Whitehouse_Hackathon/index.html

### Questions, Comments, Suggestions?

If you have any questions submit them to connect@bcic.ca or post your questions in the comments section below.

**Comment by sasha-ruby** [comment]
Hi Martin,

in the **How to Contribute (How to Apply)** section above, it is said that "the ‘Letter of Interest’ can be a maximum of two-pages", while in the PDF file itself (which is already 4 pages long), it is said that "The ‘Letter of Interest’ should be a maximum of six-­‐pages".
Also, space available in each question of the LOI is limited to one row. How exactly are the applicants supposed to expand that space and fill in answers?
Can you please clarify?

Thanks,
Sasha

**Comment by harpreetsingh91** [comment]
I have the same query as @sasha-ruby. How can I fill in the answers when there is just one row?

**Comment by MonkmanMH** [comment]
Hello @sasha-ruby and @harpreetsingh91 (and anyone else who is following this thread). Below is the response from Nadine Diner, of the BC Innovation Council:

>Hello Sasha
>
>Regarding your question on Github, please find the corrected material at the link below.
>http://bcic.ca/news/blog/75000-available-solve-provincial-governments-data-visualization-challenges/
>
>You will see this link includes a word format LOI for you to easily complete, and the instructions denote a six-page maximum length to the LOI, so you have space for your responses.
>
>If you would still like to proceed with submitting an LOI, please contact connect@bcic.ca. The deadline is 4pm today, but we are glad to discuss a slight extension if necessary.
>
>Regards, Nadine
>
>Nadine Diner
>Director of Industry Initiatives
>Industry and Innovation Group
