### ISSUE TITLE
openshift environments/containers

### ISSUE THREAD

**Issue by cpsievert** [bcgov/housing-data-visualization-project#2]
In #1, one of the evaluation criteria is:

> Does the code run on the Province of B.C. DevOps platform (a Docker / OpenShift environment). This is much easier if you setup up the infrastructure before you start coding (10 points).

Do you have a specific container/environment available that you'd like us to build off of?

**Comment by MonkmanMH** [comment]
I asked @ccoldwell, and this is the bulk of his reply:

The [_simple-R-shiny_ repo](https://github.com/bcgov/simple-R-shiny) could be used as an example, or forked and used wholesale.

Chris goes on to say:

> If they are using different technologies, then it would be good if they attempted to run up a local OpenShift environment and use it as a test for their configurations.
>
>If OpenShift presents an issue, we would at very least like to see the results in Docker so they are easy for us to fire up and work through without having to set up other environments.  We are following a standard now of having a setup script that builds the docker image, and a dev script that fires it up into a container and places us in a position to run the code or work on it.  Something along those lines, with a bit of English in a README would be most welcome.

I hope this helps.

**Comment by cpsievert** [comment]
Thanks, this helps. I have a docker image now, which I can run just fine locally, but when deployed on openshift, I run into a permissions issue. Is this something that should be fixed via the config file `/etc/shiny-server/shiny-server.conf`?

http://simple-r-shiny-bcviz.44fs.preview.openshiftapps.com/

**Comment by MonkmanMH** [comment]
Hopefully @ccoldwell can chime in--he's got the expertise in this area.
